#! /bin/env bash

## Identify all installed versions of R
path=/cbc/shared/software
versions=$(ls $path | grep "IGV[-][0-9]" | cut -c 5- | tr '\n' ' ')
echo $versions

for version in ${versions}; do
  echo "Version: ${version}"
## Here document for RSP template
cat << EOF > ${version}.lua
help([[
IGV: The Integrative Genomics Viewer
]])

local name = "IGV"
local version = "${version}"
whatis("Version: " .. version)
whatis("Keywords: ")
whatis("URL: https://software.broadinstitute.org/software/igv/")
whatis("Description: The Integrative Genomics Viewer (IGV) is a high-performance visualization tool for interactive exploration of large, integrated genomic datasets. It supports a wide variety of data types, including array-based and next-generation sequence data, and genomic annotations.")

-- Local variables
local cbc_shared = "/home/shared/cbc"
local cbc_software = cbc_shared .. "/software"
local home = cbc_software .. "/" .. name .. "-" .. version
prepend_path("PATH", home)
set_alias("igv", home .. "/igv.sh")
EOF
done
