#! /bin/env bash

## Identify all installed versions
path=/cbc/shared/software_cbc
versions=$(ls $path | grep "samtools[-][0-9]" | sed 's/samtools-//g' | tr '\n' ' ')
echo $versions

for version in ${versions}; do
  echo "Version: ${version}"
## Here document for template
cat << EOF > ${version}.lua
help([[
Samtools: Tools (written in C using htslib) for Manipulating Next-Generation Sequencing Data
]])

local name = myModuleName()
local version = myModuleVersion()
whatis("Version: " .. version)
whatis("Keywords: sequencing")
whatis("URL: http://www.htslib.org/")
whatis("Description: Samtools is a suite of programs for interacting with high-throughput sequencing data.  Example: \`samtools --version\`")

load("cbc-devel")

local path = "/home/shared/cbc/software_cbc"
local home = path .. "/" .. name .. "-" .. version

prepend_path("PATH", home .. "/bin")
prepend_path("MANPATH", home .. "/share/man")

-- samtools (< 1.6):
prepend_path("PATH", home)
prepend_path("PATH", home .. "/bcftools")
prepend_path("PATH", home .. "/misc")

EOF
done
