#!/bin/env bash

## PBS prologue and epilogue scripts are run with almost no environment variables
## are set. They are called with arguments that helps up identify the most important
## settings (that we would otherwise get from environment variables).
##
## Furthermore, environment variables exported in these scripts are _not_ exported
## to the job environment.
##
## These script can be called explicitly at job submission, e.g.
## qsub -l prologue=~/.pbs.d/prologue.d/foo.sh epilogue=~/.pbs.d/epilogue.d/bar.sh
##
## See also: http://docs.adaptivecomputing.com/torque/3-0-5/a.gprologueepilogue.php
if [[ -z "$PBS_JOBID" ]]; then
    PBS_JOBID=$1
fi
if [[ -z "$USER" ]]; then
    USER=$2
fi

## Do nothing?
if [[ -z "$USER" ]]; then return; fi
if [[ -z "$PBS_JOBID" ]]; then return; fi

## Root folders
SCRATCH_ROOT=/scratch
TMP_ROOT=/tmp

## User-specific working directories on the compute node
SCRATCH_USER="$SCRATCH_ROOT/$USER"
TMP_USER="$TMP_ROOT/$USER"

## Create user-specific folders
for dir in "$TMP_USER" "$SCRATCH_USER"; do
    if [[ ! -d "$dir" ]]; then
        mkdir -p "$dir"
    fi
done

## Job-specific working directories on the compute node
JOB_PATH="jobs/$PBS_JOBID"
SCRATCH_JOB="$SCRATCH_USER/$JOB_PATH"
TMP_JOB="$TMP_USER/$JOB_PATH"

## Create each job-specific folders
for dir in "$TMP_JOB" "$SCRATCH_JOB"; do
    if [[ ! -d "$dir" ]]; then
        mkdir -p "$dir"
    fi
done


FOOBAR=abc
export BARFOO=def

