#! /bin/env bash

## Identify all installed versions
path=/cbc/shared/software
versions=$(ls $path | grep "bowtie2[-][0-9]" | sed 's/bowtie2-//g' | tr '\n' ' ')
echo $versions

for version in ${versions}; do
  echo "Version: ${version}"
## Here document for template
cat << EOF > ${version}.lua
help([[
Bowtie2
]])

local name = "bowtie2"
local version = "${version}"
whatis("Version: " .. version)
whatis("Keywords: sequencing")
whatis("URL: http://bowtie-bio.sourceforge.net/bowtie2/index.shtml")
whatis("Description: Bowtie 2 is an ultrafast and memory-efficient tool for aligning sequencing reads to long reference sequences.")

-- Local variables
local cbc_shared = "/home/shared/cbc"
local cbc_software = cbc_shared .. "/software"

local home = cbc_software .. "/" .. name .. "-" .. version
prepend_path("PATH", home)
EOF
done
