#! /bin/env bash

## Identify all installed versions of R
path=/cbc/shared/software_cbc/R
system=$(ls $path | grep -E "^R[-][0-9][.][0-9]+[.][0-9]-system$")
releases=$(ls $path | grep -E "^R[-][0-9][.][0-9]+[.][0-9]-20[0-9]+$")
patched=$(ls $path | grep -E "^R[-][0-9][.][0-9]+[.][0-9]patched-20[0-9]+$" | tail -1)
devel=$(ls $path | grep -E "^R[-][0-9][.][0-9]+[.][0-9]devel-20[0-9]+$" | tail -1)
subdirs="$system"$'\n'"$releases"$'\n'"$patched"$'\n'"$devel"
echo $subdirs

for subdir in ${subdirs}; do
  version=$(echo $subdir | sed -E 's/^R-//g' | sed -E 's/-(20[0-9]+|system)$//g')
  echo "R installation: ${subdir}"
  echo "R version: ${version}"
## Here document for RSP template
cat << EOF > ${version}.lua
help([[
R: The R Programming Language
]])

local name = myModuleName()
local version = myModuleVersion()
whatis("Version: " .. version)
whatis("Keywords: Programming, Statistics")
whatis("URL: https://www.r-project.org/")
whatis("Description: The R programming language. Example: \`R --version\` and \`Rscript --version\`.")

local path = os.getenv("SOFTWARE_ROOT_CBC")
local home = path .. "/R/${subdir}"
prepend_path("PATH", home .. "/bin")
prepend_path("MANPATH", home .. "/share/man")
EOF
done

ln -fs 3.3.3.lua oldrel.lua
ln -fs 3.4.4.lua release.lua
ln -fs 3.4.3patched.lua patched.lua
ln -fs 3.5.0devel.lua devel.lua
ln -fs 3.4.4.lua default
