#! /bin/env bash

## Identify all installed versions of Python
path=/cbc/shared/software
versions=$(ls $path | grep "Python[-][0-9]" | cut -c 8- | tr '\n' ' ')
echo $versions

for version in ${versions}; do
  echo "Python version: ${version}"
## Here document for RSP template
cat << EOF > ${version}.lua
help([[
Python - The Python Programming Language
]])

-- local name = myModuleName()
local name = "Python"
local version = myModuleVersion()
whatis("Version: " .. version)
whatis("Keywords: Programming")
whatis("URL: https://www.python.org/")
whatis("Description: Python is a programming language that lets you work quickly and integrate systems more effectively.  Example: \`python --version\`.")

local path = "/home/shared/cbc/software"
local home = path .. "/" .. name .. "-" .. version

prepend_path("PATH", home .. "/bin")
prepend_path("LD_LIBRARY_PATH", home .. "/lib")
prepend_path("MANPATH", home .. "/share/man")
prepend_path("PYTHONPATH", home .. "/lib/python2.7")
EOF
done

ln -fs 2.7.9.lua default

