#! /bin/env bash

## Identify all installed versions of Python
path=/cbc/shared/software
versions=$(ls $path | grep "Python[-][0-9]" | cut -c 8- | tr '\n' ' ')
echo $versions

for version in ${versions}; do
  echo "Python version: ${version}"
## Here document for RSP template
cat << EOF > ${version}.lua
help([[
The Python Programming Language
]])

-- local name = myModuleName()
local name = "Python"
local version = myModuleVersion()
whatis("Version: " .. version)
whatis("Keywords: Programming")
whatis("URL: https://www.python.org/")
whatis("Description: The Python programming language")

-- Local variables
local cbc_shared = "/home/shared/cbc"
local cbc_software = cbc_shared .. "/software"

local home = cbc_software .. "/" .. name .. "-" .. version
prepend_path("PATH", home .. "/bin")
prepend_path("LD_LIBRARY_PATH", home .. "/lib")
prepend_path("PYTHONPATH", home .. "/lib/python2.7")
EOF
done

#ln -fs release.lua default
