#!/usr/bin/env bash

###################################################################
# Author: Henrik Bengtsson <hb@biostat.ucsf.edu>
#
# Description:
# Sets up the PATH to use the most recent versions of software
# installed by different users.
#
# Usage:
# Add the following command to your ~/.bashrc script:
#   source /home/shared/cbc/bashrc
###################################################################

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Record original state
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if test "${PATH_SYSTEM}" == ""; then
  export PATH_SYSTEM=${PATH}
fi

# Setup SHARED_ROOT
export SHARED_ROOT=/home/shared/cbc

# Useful functions
source ${SHARED_ROOT}/bin/includes.bash


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Setup PATH depending on system
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export PATH=${PATH_SYSTEM}

# Added ~/bin/
if ! test -d "${HOME}/bin"; then
  mkdir ${HOME}/bin
fi
appendPath ${HOME}/bin


export HOST=`uname -n`
export HOST_SHORT=${HOST/.*/}
export ARCH=`uname -m`
export ISCOMPUTENODE=0
if [[ ${HOST_SHORT} =~ n[0-9]{1,2} ]]; then
  export ISCOMPUTENODE=1
fi
## echo ISCOMPUTENODE=$ISCOMPUTENODE


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SETUP COMPUTE NODES
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export CLUSTER_SCHEDULER="TORQUE"
export CLUSTER_HEADNODE="cclc01"
export CLUSTER_NODES="n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 n14 n15 n17 n18 n19 n20 n21 n22 n23 n24 n25 n26 n27"

if [[ "${ISCOMPUTENODE}" = "1" ]]; then
    prependPath ${SHARED_ROOT}/bin/compute_nodes_only
fi


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Misc
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Never use /usr/libexec/openssh/gnome-ssh-askpass
unset SSH_ASKPASS


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Python
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##prependPath /opt/local/bin # Python 2.6.5
prependPath ${SHARED_SOFTWARE}/Python-2.7.4/bin
# Anaconda [https://store.continuum.io/cshop/anaconda/],
# which includes Python
prependPath /home/shared/cbc/software_cbc/anaconda/bin


PYTHON_VERSION=$(python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]));')
PYTHON_HOME=$(which python)

if test "${PYTHONPATH_SYSTEM}" == ""; then
  export PYTHONPATH_SYSTEM=${PYTHONPATH}
fi
export PYTHONPATH=${PYTHONPATH_SYSTEM}

# Add user-specific Python binaries
dir=${HOME}/.local/bin
if ! test -d "${dir}"; then
  mkdir -p "${dir}"
fi
export PYTHONPATH=${dir}:${PYTHONPATH}
prependPath ${dir}

# Add site-wide Python packages
if test "${PYTHON_VERSION}" == "2.6"; then
  PYTHON_SITE=/opt/local/lib/python2.6/site-packages
else
  PYTHON_SITE=$(dirname $(dirname $PYTHON_HOME))/lib/python${PYTHON_VERSION}
fi
export PYTHONPATH=${PYTHONPATH}:${PYTHON_SITE}




# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Development, e.g. gcc
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#prependPath /opt/llvm/llvm-3.5.0/bin
export GCC_HOME=/opt/gcc/gcc-4.9.2
if test -d "${GCC_HOME}"; then
    prependPath ${GCC_HOME}/bin
    export LD_LIBRARY_PATH="${GCC_HOME}/lib64:${LD_LIBRARY_PATH}"
fi



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# BUILDS
#
# ./configure --prefix=${SHARED_ROOT}/local/
# make
# make install
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export CPPFLAGS="-I${SHARED_ROOT}/local/include $CPPFLAGS"
export LDFLAGS="-L${SHARED_ROOT}/local/lib $LDFLAGS"

## TODO: Make available to all users /HB 2016-12-01
#if test $USER == "henrik" || test $USER == "cbctest"; then
#export LD_LIBRARY_PATH="${SHARED_ROOT}/local/lib:${LD_LIBRARY_PATH}"
#fi



# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Default editor for 'svn commit' and others
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if test "${EDITOR}" = ""; then
  export EDITOR="emacs -nw"
fi


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# CBC-shared .bashrc.d/
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [[ -d "${SHARED_ROOT}/.bashrc.d" ]]; then
    for ff in $(find "${SHARED_ROOT}/.bashrc.d/" -type f ! -name '*~'); do
      if [[ "${USER}" = "henrik" ]]; then >&2 echo "${ff}"; fi
      source "${ff}"
    done
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SHARED SOFTWARE
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
prependPath ${SHARED_ROOT}/bin
prependPath ${SHARED_ROOT}/local/bin


###################################################################
# HISTORY:
# 2014-05-05
# o Added cran().
# 2012-04-28
# o Extracted and shared.
###################################################################
