#!/usr/bin/env bash

###################################################################
# Usage:
# Add the following command to your ~/.bashrc script:
#   source /home/shared/cbc/bashrc
#
# Description:
# Sets up the PATH to use the most recent versions of software
# installed by different users.
#
# Author: Henrik Bengtsson <henrik.bengtsson@ucsf.edu>
###################################################################

function is_function() {
    type $1 &> /dev/null
    if [[ $? -eq 0 ]]; then echo 1; else echo 0; fi
}

## TEMPORARY WORKAROUND: Until all nodes have had /etc/bashrc copied
## we might need to have the following resourced again
if [[ "$(is_function source_d)" == "0" ]]; then
    if [[ "$USER" == "henrik" ]]; then
        echo "ERROR: This line in '/home/shared/cbc/bashrc' should not be reached!"
    fi
    source /home/shared/cbc/tipcc/.bashrc
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Record original state
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [[ "${PATH_SYSTEM}" == "" ]]; then
  export PATH_SYSTEM=${PATH}
fi
if [[ "${LD_LIBRARY_PATH_SYSTEM}" == "" ]]; then
  export LD_LIBRARY_PATH_SYSTEM=${LD_LIBRARY_PATH}
fi

# Setup SHARED_ROOT
export SHARED_ROOT=/home/shared/cbc
source ${SHARED_ROOT}/bin/includes.cbc.bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Setup PATH depending on system
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export PATH=${PATH_SYSTEM}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH_SYSTEM}

# Added ~/bin/
if [[ ! -d "${HOME}/bin" ]]; then
  mkdir ${HOME}/bin
fi
appendPath ${HOME}/bin

export HOST=`uname -n`
export HOST_SHORT=${HOST/.*/}
export ARCH=`uname -m`
export ISCOMPUTENODE=0
if [[ "${HOST_SHORT}" =~ ^n[0-9]{1,2} ]]; then
  export ISCOMPUTENODE=1
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SETUP COMPUTE NODES
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export CLUSTER_SCHEDULER="TORQUE"
export CLUSTER_HEADNODE="cclc01"
export CLUSTER_NODES="n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 n14 n15 n17 n18 n19 n20 n21 n22 n23 n24 n25 n26 n27 n28 n29 n30"

if [[ "${ISCOMPUTENODE}" = "1" ]]; then
    prependPath ${SHARED_ROOT}/bin/compute_nodes_only
fi


## FIX: Current users will use CBC Tools
if [[ ! -f ${HOME}/.cbc ]]; then touch ${HOME}/.cbc; fi


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Source different .bashrc.d/ paths
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
## CBC Tools?
export CBC_STARTUP_COMPLETED=
if [[ -f ${HOME}/.cbc ]]; then
    source_d "$SHARED_ROOT/.bashrc.d"
fi

## User's ~/.bashrc.d/ scripts?
if [[ -d "$HOME/.bashrc.d" ]]; then source_d "$HOME/.bashrc.d"; fi

