help([[
VCFtools
]])

local name = "vcftools"
local version = "0.1.13"
whatis("Version: " .. version)
whatis("Keywords: ")
whatis("URL: https://vcftools.github.io/")
whatis("Description: VCFtools is a program package designed for working with VCF files, such as those generated by the 1000 Genomes Project. The aim of VCFtools is to provide easily accessible methods for working with complex genetic variation data in the form of VCF files.")

-- Local variables
local cbc_shared = "/home/shared/cbc"
local cbc_software = cbc_shared .. "/software"

local path = cbc_software .. "/" .. name .. "-" .. version
prepend_path("PATH", path .. "/bin")
